# Generated by Django 5.2.7 on 2025-10-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=256)),
                ('height', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentMetadata',
            fields=[
                ('device_id', models.CharField(primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=42)),
            ],
        ),
    ]
